name: Node CI

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
